language: perl
perl:
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.30"

sudo: false

env:
  - INSTALL_FMODE=true
  - INSTALL_FMODE=false

install:
  - if [ $INSTALL_FMODE == 'true' ]; then cpanm FileHandle::Fmode; fi
