language: perl
perl:
  - "5.8"  # Devel::Callsite doesn't install properly on TravisCI here
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

sudo: false

env:
  - INSTALL_FMODE=true
  - INSTALL_FMODE=false

install:
  - if [ $INSTALL_FMODE -eq 'true' ]; cpanm FileHandle::Fmode; fi
